### ISSUE TITLE
Assigns coordinates to the new boxes

### ISSUE THREAD

**Issue by albertmena** [SMLC-NYSBC/ptolemy#2]
For not squared images, the box coordenates (if there is a rotation) are bad assigned. Changing [L44 and L47](https://github.com/SMLC-NYSBC/ptolemy/blob/49a30f610ad8df28f643920848a3660dd78bc9bb/ptolemy/geometry.py#L44) fix the issue.

1. get the minimum size `min_img = min(image.shape[0], image.shape[1])`
`min_rotated= min(rotated_image.shape[0], rotated_image.shape[1])`
2. set it on original_origin and rotated_origin 
```
 original_origin = [min_axi // 2, min_axi // 2]
 rotated_origin = [min_rotated // 2, min_rotated // 2]
```

**Comment by tbepler** [comment]
Thanks for reporting this! Do you have a before/after image showing the problem and the results after your patch we can look at?

**Comment by albertmena** [comment]
atlas.mrc [1812x1356]

Before:
![Screenshot from 2022-03-07 14-21-12](https://user-images.githubusercontent.com/12760268/157042257-e5af5113-f8d5-4773-a504-99c192a6f68f.png)
After my proposal:
![Screenshot from 2022-03-07 14-19-32](https://user-images.githubusercontent.com/12760268/157042319-872a0043-b7cd-4757-aba4-873f6deeefd9.png)

**Comment by ptkim1** [comment]
@albertmena thanks for finding this! Your solution is good, I've pushed the changes to fix this issue. Cheers!
